name: CI Pipeline


on:
    push:
        branches:
            - main
jobs:
    build:
        runs-on:
            ubuntu-latest



        steps:
            - name: Checkout code
              uses: actions/checkout@4
            

            - name: Say Hello
              run: echo "Hello GitHub Actions, It's my first CI Pipeline!"

            - name: List files
              run: ls -la
             


